-- 게시판 테이블 생성

CREATE TABLE BOARD (
  
    BNO         NUMBER,                             -- 글번호
    TITLE       VARCHAR2(100)   NOT NULL,           -- 제목
    CONTENT     VARCHAR2(1000)  NOT NULL,           -- 내용
    WRITER      VARCHAR2(100)   NOT NULL,           -- 작성자
    REGDATE     DATE            DEFAULT SYSDATE,    -- 등록일
    UPDATEDDATE DATE            DEFAULT SYSDATE,    -- 수정일
    CONSTRAINT  PK_BOARD        PRIMARY KEY(BNO)
);

-- 제약조건의 이름이 PK_BOARD 으로 인덱스명 PK_BOARD가 생성된다.

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD;

-- 시퀀스 명령어 

/* 

- SEQ_BOARD.NEXTVAL 시퀀스에서 다음 순번값을 자동으로 가져온다
- SEQ_BOARD.CURRVAL  시퀀스에서 현재 값을 알 수 있다.
*/
/*
    CREATE SEQUENCE my_seq1
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 1000
    NOCYCLE
    NOCACHE;
*/

drop table BOARD;

alter table BOARD;


CREATE SEQUENCE SEQ_BOARD;


DROP SEQUENCE SEQ_BOARD;



SELECT SEQ_BOARD.NEXTVAL FROM DUAL;

SELECT SEQ_BOARD.CURRVAL FROM DUAL;

INSERT INTO BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES(SEQ_BOARD.NEXTVAL, '제목', '스프링 실습', 'user02');

SELECT * FROM BOARD;


SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE FROM BOARD ORDER BY BNO DESC;

DELETE FROM BOARD WHERE CONTENT IS NOT NULL;

UPDATE BOARD SET TITLE= ? , CONTENT= ? , UPDATEDATE = SYSDATE WHERE BNO = ?;

DELETE FROM BOARD;

COMMIT;

-- 시퀀스 상태
SELECT SEQ_BOARD.CURRVAL FROM DUAL;

DROP SEQUENCE SEQ_BOARD;

-- 초기값 = 1 증가값 1
CREATE SEQUENCE SEQ_BOARD; 

-- 더미데이터

INSERT INTO BOARD(BNO, TITLE, CONTENT, WRITER)
SELECT SEQ_BOARD.NEXTVAL, TITLE,CONTENT, WRITER FROM BOARD;

COMMIT;


SELECT * FROM BOARD ORDER BY BNO ASC;
-- 최신글 순서
SELECT * FROM BOARD ORDER BY BNO DESC;

-- 인덱스 힌트

-- 별칭 
SELECT /*+INDEX_DESC(B PK_BOARD) */ BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE FROM BOARD B;
-- 별칭 미사용
SELECT /*+INDEX_DESC(BOARD PK_BOARD) */ BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE
FROM BOARD
-- 결과 없음
WHERE ROWNUM >= 5 AND ROWNUM <10;

-- ROWNUM

SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE
FROM BOARD

WHERE ROWNUM >= 5 AND ROWNUM <10;



-- 서브쿼리(인라인뷰)

SELECT RN, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE
FROM (    
    SELECT ROWNUM AS RN, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE
    FROM BOARD
     )
WHERE RN >=5 AND RN<= 10;


-- 페이지 쿼리


SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE

FROM 
(
SELECT  /*+INDEX_DESC(board pk_board) */ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE 
FROM    BOARD -- 내림차순
WHERE   ROWNUM <= #{PAGENUM} * #{AMOUNT}
)
WHERE RN > (#{PAGENUM} -1) * #{AMOUNT} 


-- Page1
SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE

FROM 
(
SELECT  /*+INDEX_DESC(board pk_board) */ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE 
FROM    BOARD -- 내림차순
WHERE   ROWNUM <= 1* 5
)
WHERE RN > (1 -1) * 5;

-- PAGE2
SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE

FROM 
(
SELECT  /*+INDEX_DESC(board pk_board) */ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE 
FROM    BOARD -- 내림차순
WHERE   ROWNUM <= 2* 5
)
WHERE RN > (2 -1) * 5;

-- PAGE3
SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE

FROM 
(
SELECT  /*+INDEX_DESC(board pk_board) */ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDDATE 
FROM    BOARD -- 내림차순
WHERE   ROWNUM <= 3* 5
)
WHERE RN > (3 -1) * 5;

--  테이블 전체 갯수
SELECT COUNT(*) FROM BOARD;









